#!/bin/bash

g++ -Wall -Wextra -Werror -Wstrict-prototypes -Wconversion -Wsign-conversion -Wfloat-equal -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wuninitialized -Wredundant-decls -Wwrite-strings -pedantic -std=c++11 $*

